# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0003_auto_20190308_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
