# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
