# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0005_auto_20190308_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='description',
        ),
    ]
