# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0007_auto_20190309_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='caption',
            field=models.CharField(max_length=250),
        ),
    ]
