# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0008_auto_20190311_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='picture',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
